### ISSUE TITLE
Message Signing Stopped Working on mobile

### ISSUE THREAD

**Issue by eamon-neoswap** [secretkeylabs/xverse-core#158]
Hey Xverse team. Did something change on mobile for signing messages? Our Stacks signing worked using 
```
import { useOpenSignMessage } from '@micro-stacks/react'
const { openSignMessage } = useOpenSignMessage();
const signature = await openSignMessage({
  message: nonce as string,
})
```

but doesn't seem to work anymore on mobile. Seems to work on desktop.

**Comment by eamon-neoswap** [comment]
@yknl Any update on this issue?

**Comment by yknl** [comment]
This issue should be fixed.
