### ISSUE TITLE
Bug Report: Secondary wallet in Mobile Wallet reports incorrect public key

### ISSUE THREAD

**Issue by chironjit-neoswap** [secretkeylabs/xverse-core#190]
Not sure if this is the best place to report, but since the mobile app is not public, I am posting it here:

When we the app developer try to get the public key from the user's second account on the mobile wallet, the ordinals public key is incorrect. It shows the public key of the first wallet

The issue was reported to us originally by a user but I have managed to replicate it on my device (Android).

Can validate the issue here: https://test-xverse.vercel.app/ 
(repo: https://github.com/chironjit-neoswap/test-xverse)

**Comment by m-aboelenein** [comment]
hey @chironjit-neoswap  thanks for reporting this issue we were able to reproduce and implement a fix that should be out pretty soon 🙏

**Comment by yknl** [comment]
This should be fixed.
