### ISSUE TITLE
Make wallet compatible with sbtc 

### ISSUE THREAD

**Issue by friedger** [secretkeylabs/xverse-core#234]
Why are xverse btc address and leather wallet btc address different?

Which address should be used to receive sbtc when providing a sign message?

See also https://discord.com/channels/621759717756370964/1150794576433524776/1150794581638660176

**Comment by yknl** [comment]
Are you referring to Xverse's wrapped segwit BTC address vs native segwit BTC address?

Do you have more context on the receive sBTC question? The link is just an announcement.

**Comment by friedger** [comment]
I'll need to rewrite this when I have better understanding...
