### ISSUE TITLE
Ledger PSBT extra input

### ISSUE THREAD

**Issue by mi-yu** [secretkeylabs/xverse-core#308]
I noticed that an extra input is added to the PSBT when signing with Ledger to work around a bug: https://github.com/secretkeylabs/xverse-core/blob/0bd8001922ae15f2c17c20b46f7114724cb5b10f/ledger/psbt.ts#L143-L154, is it possible to remove this extra input before returning the signed PSBT?

**Comment by teebszet** [comment]
hi @mi-yu! 

thanks for raising this, the fix will go out next web-extention release (0.27.0) 😄

**Comment by mi-yu** [comment]
thank you!

**Comment by mi-yu** [comment]
Hi following up, do you know when 0.27.0 will go out?

**Comment by teebszet** [comment]
should be this week

**Comment by teebszet** [comment]
this was released
