### ISSUE TITLE
Incorrect stacking info on iOS app

### ISSUE THREAD

**Issue by fyang1024** [secretkeylabs/xverse-core#332]
I am not sure if this is the right place to raise the issue, but I cannot find the iOS app repo.
I am doing solo stacking using Leather Wallet desktop app. My iOS XVerse wallet on my iPhone shows that I am pooling in XVerse pool

Below is what is shown on the Leather Wallet desktop, which is correct. I initiated solo stacking from the leather wallet
![Screenshot 2023-12-31 at 12 52 40 pm](https://github.com/secretkeylabs/xverse-core/assets/20808865/6cefe977-468a-4f6f-8d54-844650e6e7a9)

Below is the screenshot of my XVerse wallet on my iPhone. 
The info in the red box below are wrong info.
I didn't delegate the stacking to the pool
"POOL REWARD ADDRESS" is actually my personal reward address
"YOUR REWARD ADDRESS" is not my reward address

![IMG_7453](https://github.com/secretkeylabs/xverse-core/assets/20808865/f402aa7e-f33d-48b1-98bf-85d4943cd9f1)

**Comment by abdulhaseeb4239** [comment]
thanks for raising the issue @fyang1024, can you share your STX address so we can investigate?

**Comment by fyang1024** [comment]
nvm, I don't see the wrong info anymore. It might be upstream API issue that has been fixed
