### ISSUE TITLE
Error "there is a chance that input is unspendable" when listing on MagicEden.io, Magisat.io

### ISSUE THREAD

**Issue by donnlee** [secretkeylabs/xverse-core#340]
![magiceden chance unspendable, console Screenshot from 2024-01-02](https://github.com/secretkeylabs/xverse-core/assets/1100053/a5ce4131-5fe5-432f-b528-444a2feb7c10)

NOTE: The substring was updated on Jan 5 to `allowUnknownOutputs=true` (lib btc-signer).

Throws on magiceden.io and magisat.io when you try to list a rare sats utxo.
Repro's on Chrome and Brave, Linux and Mac, and on Xverse iOS app.

I chased this issue for 6 days and I think I've found the root cause. There are no search hits on google and 1 report on twitter/X (in Chinese). Two users reported the error in MagicEden's discord last month (no follow-up data).

Xverse seems to throw the error when the transaction has an OP_RETURN output along with normal utxo's.
I'm trying to list a rare sats utxo sitting in this txn:
https://mempool.space/tx/20a3c79e7e421122036e0efafcf5414840b5295e7ae479e1af488d17f12d9734
(op_return is the last output)

Attempting to list any one of those 330 sat utxo's throws the error.
There is no Xverse error if I simply transfer the utxo to another address.

The error is thrown in btc-signer here:
https://github.com/paulmillr/scure-btc-signer/blob/342ad080071d7969f170ccfd3a2a8ac3aa25a03d/index.ts#L2115

Xverse raises that error here:
https://github.com/secretkeylabs/xverse-core/blob/1caa304fe67064b6a70c0292332b46e0f7c8a2b3/transactions/psbt.ts#L136

My theory is: btc-signer is iterating over every output here:
https://github.com/paulmillr/scure-btc-signer/blob/342ad080071d7969f170ccfd3a2a8ac3aa25a03d/index.ts#L1827
and when it hits the op_return, it throws the error. But this is not certain.

```
for (const o of parsed.outputs) tx.addOutput(o);
```

One fix is to pass `allowUnknownOutputs=true` as mentioned by the dev of btc-signer:
https://github.com/paulmillr/scure-btc-signer/issues/66

Another idea is: Why does Xverse (or btc-signer) need to look at every output when I am listing just one utxo? Can it sign the one utxo and ignore the other outputs?

Steps to repro
I don't know how to simulate rare sats on testnet. On mainnet, create a transaction with a rare sats utxo and an op_return output. Try to list the rare sats utxo.

The following issue mentions op_return and this error, which brought me to today.
https://github.com/paulmillr/scure-btc-signer/issues/59

```
Failed to sign transaction
Error signing PSBT Error: Transaction/output: unknown output script type, there is a chance that input is unspendable. Pass allowUnknownOutputs=true, if you sure
```

cc: @victorkirov

**Comment by donnlee** [comment]
I see xverse-core sets `allowUnknownOutputs: true` in `xverse-core/connect/bip322Signature.ts`, so maybe there is hope for me 😅

**Comment by donnlee** [comment]
I patched node_modules/@scure/btc-signer/index.js and built xverse-web-extension.
And it worked. I can list those utxo's on magiceden.io
Xverse instructions for building the Chrome extension were very helpful.
Great job by the Xverse team ❤️

**Comment by victorkirov** [comment]
@donnlee thanks for the great write up on the issue 🙇 There definitely shouldn't be an error for using a UTXO from a transaction with an OP_RETURN output if that output is not being used. I don't think the scure signer library does introspection of the transactions, it only uses what you pass to it, so it's most likely something we need to fix on our side.

**Comment by donnlee** [comment]
Fixed in btc-signer. See https://github.com/paulmillr/scure-btc-signer/issues/66
