### ISSUE TITLE
`crypto` could not be found within the project

### ISSUE THREAD

**Issue by friedger** [secretkeylabs/xverse-core#347]
When setting up a new react-native project using xverse-core, I get the following error
```
Error: Unable to resolve module crypto from /home/code/myproject/node_modules/@secretkeylabs/xverse-core/dist/wallet/index.js: crypto could not be found within the project or in these directories:
  node_modules/@secretkeylabs/xverse-core/node_modules
``` 
The crypto package is part of node, do I need to do a specific setup for crypto?

I am using
```
    "react": "18.2.0",
    "react-native": "0.73.2",
```

**Comment by victorkirov** [comment]
Crypto is a Node module available for pplicaitons running in Node, but if you're building a React app, the crypto module is not available in the browser (e.g. Chrome).

There are packages available that can add the crypto package for you for browser side code.

**Comment by fedeerbes** [comment]
Hi @friedger, for a react native app you can use https://github.com/margelo/react-native-quick-crypto

**Comment by friedger** [comment]
Thank you
