### ISSUE TITLE
Seed Phrase Recovery

### ISSUE THREAD

**Issue by 0xAzures** [secretkeylabs/xverse-core#360]
I am new to GitHub and I hope it's the right place to post this. 

Today I try to switch my phone and I had to restore my wallet on the new phone. I was close to a heart attack because it didn't work out like expected. 

Here is why and why I think this process could be smoother.

My mistake upfront. The Xverse app at least on my phone (iPhone 14P Pro) only showed 18 words instead of 24.  To see the remaining six words I had to manually with my finger move up the screen. 

It took me a while to understand that they're only 18 words displayed so I tried to punch in this 18 words on my other phone and the wallet told me that it's the wrong seed.
Double checked all words again, no access....again...again...retyped...heart attack....

I now *afterwards* understand that this might be even a security feature because even if you make a screenshot, you won't have one photo with all the words on one shot. 

But the app could provide much more guidance! 

On top the app doesn't provide more information on how to type in the words. I had to search the internet in order to understand that I have to type in the words without commas just a one space between the words and no break.again more guidance for the user please!

Change your phone with MetaMask and they provide a QR and you take a photo and voila your seed is transferred. Try it, it's very smooth.

I hope this helps to improve the app. Cheers.

**Comment by teebszet** [comment]
thanks for the feedback 🙏 and apologies for the late response. I've forwarded this on to our UX team 😄
