### ISSUE TITLE
Add options for parent and metadata when create ordinals with xverse wallet and sat-connect module

### ISSUE THREAD

**Issue by devlancer412** [secretkeylabs/xverse-core#372]
I think we can add additional metadata and parent hash when create ordinals. But Xverse wallet api and sat-connect doesn't have such options. I saw this codebase and noticed that it uses external api. Please provide such options in api

**Comment by teebszet** [comment]
hi @devlancer412 , thanks for using sats-connect and reaching out!

if you still need help, please create an issue on the https://github.com/secretkeylabs/sats-connect/issues repo 😃
