### ISSUE TITLE
Question: Does signPsbt API support for signing a taproot P2TR multi-sig transaction?

### ISSUE THREAD

**Issue by mint-pz** [secretkeylabs/xverse-core#388]
My context is: I created a taproot P2TR multi-sig wallet from my wallet (xverse) and another, then made a PSBT with that multi-sig wallet. Whether I can sign that PSBT by the signPsbt API (https://docs.xverse.app/sats-connect/bitcoin-methods/signpsbt)

Someone tried to sign by Unisat wallet here: https://github.com/bitcoinjs/bitcoinjs-lib/issues/2111#issuecomment-2259271748

**Comment by victorkirov** [comment]
Hey @mint-pz 

Yes, it is supported. Just make sure that you're using the public key for the ordinals address in your multisig lock script, then send the PSBT to Xverse via sats connect, specifying which inputs should be signed with the taproot address.

Just note that the PSBT in the response will have a partial sig which you'll need to use to create the final unlocking script.

**Comment by mint-pz** [comment]
> Hey @mint-pz
> 
> Yes, it is supported. Just make sure that you're using the public key for the ordinals address in your multisig lock script, then send the PSBT to Xverse via sats connect, specifying which inputs should be signed with the taproot address.
> 
> Just note that the PSBT in the response will have a partial sig which you'll need to use to create the final unlocking script.

Thanks for ur kind reply!

**Comment by mint-pz** [comment]
@victorkirov, if possible, could you have an example of it?

**Comment by bof195** [comment]
I have the same issue, any example could help!

**Comment by shallcdn** [comment]
> My context is: I created a taproot P2TR multi-sig wallet from my wallet (xverse) and another, then made a PSBT with that multi-sig wallet. Whether I can sign that PSBT by the signPsbt API (https://docs.xverse.app/sats-connect/bitcoin-methods/signpsbt)
> 
> Someone tried to sign by Unisat wallet here: [bitcoinjs/bitcoinjs-lib#2111 (comment)](https://github.com/bitcoinjs/bitcoinjs-lib/issues/2111#issuecomment-2259271748)

I am encountering the same issue. I have been trying to find a document for it, but so far, I have had no luck.

**Comment by victorkirov** [comment]
@mint-pz @bof195 @shallcdn are you guys using bitcoinjs-lib? We almost exclusively use scure btc signer, so it would be much easier to give an example with that. Maybe I can write up and example with scure and you can translate it to bitcoinjs-lib if you're using that. Will try put something together today.

**Comment by mint-pz** [comment]
> @mint-pz @bof195 @shallcdn are you guys using bitcoinjs-lib? We almost exclusively use scure btc signer, so it would be much easier to give an example with that. Maybe I can write up and example with scure and you can translate it to bitcoinjs-lib if you're using that. Will try put something together today.

That looks good to me sir!

**Comment by victorkirov** [comment]
```
import { base64 } from "@scure/base";
import * as bip32 from "@scure/bip32";
import * as bip39 from "@scure/bip39";
import * as btc from "@scure/btc-signer";

const mnemonic =
  "action action action action action action action action action action action action";

const run = async () => {
  // ========= SETUP =========
  const seed = await bip39.mnemonicToSeed(mnemonic);
  const master = bip32.HDKey.fromMasterSeed(seed);

  const taprootPath = "m/86'/0'/0'/0/0'";
  const taprootSigner = master.derive(taprootPath);
  // this is effectively the public key you would have received from the wallet for the ordinals address
  const taprootPubKey = taprootSigner.publicKey!;
  const taprootPubKeyXOnly = taprootPubKey.slice(1);

  const secondSigner = master.derive("m/86'/0'/0'/0/1");
  // this is a second public key we will use for the multisig
  // this would be one you generate in your backend for the second signer
  const secondPubKey = secondSigner.publicKey!;
  const secondPubKeyXOnly = secondPubKey.slice(1);

  // this is the internal multisig locking script
  const msLockingScript = btc.p2tr_ns(2, [
    taprootPubKeyXOnly,
    secondPubKeyXOnly,
  ]);
  // this is the taproot locking script with the multisig script in the script unlock path
  const p2Multisig = btc.p2tr(undefined, msLockingScript);

  console.log("P2TR Multisig address:", p2Multisig.address);

  // ========= GENERATE TRANSACTION  =========
  // now we'll use the above locking script in a fictitious txn
  const txn = new btc.Transaction();

  // we'll add a dummy input from our multisig address
  txn.addInput({
    txid: "0000000000000000000000000000000000000000000000000000000000000000",
    index: 0,
    witnessUtxo: {
      script: p2Multisig.script,
      amount: 1000000n,
    },
    tapLeafScript: p2Multisig.tapLeafScript,
  });

  // we'll add a dummy output to some address for 999000 sats with the remaining 1000 sats being used as fees
  txn.addOutputAddress("bc1qar0srrr7xfkvy5l643lydnw9re59gtzzwf5mdq", 999000n);

  // This is the PSBT that we would be sent to the wallet for signing
  // You would need to specify the ordinals address to sign index 0
  const psbtBase64 = base64.encode(txn.toPSBT());

  console.log("PSBT to send to wallet via sats-connect:", psbtBase64);

  // ========= SIGN TRANSACTION  =========
  // this is effectively what the wallet would do internally
  const psbt = btc.Transaction.fromPSBT(base64.decode(psbtBase64));
  psbt.signIdx(taprootSigner.privateKey!, 0);

  // This is what the wallet would send back to your dapp in the response from sats-connect
  const signedPsbtBase64 = base64.encode(psbt.toPSBT());

  // ========= FINALIZE TRANSACTION  =========
  // Once you have the above signed PSBT, you can finalize it in your dapp as follows
  const signedTxn = btc.Transaction.fromPSBT(base64.decode(signedPsbtBase64));

  // Note that the user's signature lives in signedTxn.inputs[0].tapScriptSig[0]
  // In this scenario, we don't need to do anything with it as the order of the multisig has the user's pub key first
  // so we can just sign with our key
  // If the order was different, you would need to swap the signatures
  signedTxn.signIdx(secondSigner.privateKey!, 0);

  signedTxn.finalize();

  // this is the final signed transaction that you can broadcast
  console.log("Final signed transaction:", signedTxn.hex);
};

run();

```

**Comment by shallcdn** [comment]
> ```
> import { base64 } from "@scure/base";
> import * as bip32 from "@scure/bip32";
> import * as bip39 from "@scure/bip39";
> import * as btc from "@scure/btc-signer";
> 
> const mnemonic =
>   "action action action action action action action action action action action action";
> 
> const run = async () => {
>   // ========= SETUP =========
>   const seed = await bip39.mnemonicToSeed(mnemonic);
>   const master = bip32.HDKey.fromMasterSeed(seed);
> 
>   const taprootPath = "m/86'/0'/0'/0/0'";
>   const taprootSigner = master.derive(taprootPath);
>   // this is effectively the public key you would have received from the wallet for the ordinals address
>   const taprootPubKey = taprootSigner.publicKey!;
>   const taprootPubKeyXOnly = taprootPubKey.slice(1);
> 
>   const secondSigner = master.derive("m/86'/0'/0'/0/1");
>   // this is a second public key we will use for the multisig
>   // this would be one you generate in your backend for the second signer
>   const secondPubKey = secondSigner.publicKey!;
>   const secondPubKeyXOnly = secondPubKey.slice(1);
> 
>   // this is the internal multisig locking script
>   const msLockingScript = btc.p2tr_ns(2, [
>     taprootPubKeyXOnly,
>     secondPubKeyXOnly,
>   ]);
>   // this is the taproot locking script with the multisig script in the script unlock path
>   const p2Multisig = btc.p2tr(undefined, msLockingScript);
> 
>   console.log("P2TR Multisig address:", p2Multisig.address);
> 
>   // ========= GENERATE TRANSACTION  =========
>   // now we'll use the above locking script in a fictitious txn
>   const txn = new btc.Transaction();
> 
>   // we'll add a dummy input from our multisig address
>   txn.addInput({
>     txid: "0000000000000000000000000000000000000000000000000000000000000000",
>     index: 0,
>     witnessUtxo: {
>       script: p2Multisig.script,
>       amount: 1000000n,
>     },
>     tapLeafScript: p2Multisig.tapLeafScript,
>   });
> 
>   // we'll add a dummy output to some address for 999000 sats with the remaining 1000 sats being used as fees
>   txn.addOutputAddress("bc1qar0srrr7xfkvy5l643lydnw9re59gtzzwf5mdq", 999000n);
> 
>   // This is the PSBT that we would be sent to the wallet for signing
>   // You would need to specify the ordinals address to sign index 0
>   const psbtBase64 = base64.encode(txn.toPSBT());
> 
>   console.log("PSBT to send to wallet via sats-connect:", psbtBase64);
> 
>   // ========= SIGN TRANSACTION  =========
>   // this is effectively what the wallet would do internally
>   const psbt = btc.Transaction.fromPSBT(base64.decode(psbtBase64));
>   psbt.signIdx(taprootSigner.privateKey!, 0);
> 
>   // This is what the wallet would send back to your dapp in the response from sats-connect
>   const signedPsbtBase64 = base64.encode(psbt.toPSBT());
> 
>   // ========= FINALIZE TRANSACTION  =========
>   // Once you have the above signed PSBT, you can finalize it in your dapp as follows
>   const signedTxn = btc.Transaction.fromPSBT(base64.decode(signedPsbtBase64));
> 
>   // Note that the user's signature lives in signedTxn.inputs[0].tapScriptSig[0]
>   // In this scenario, we don't need to do anything with it as the order of the multisig has the user's pub key first
>   // so we can just sign with our key
>   // If the order was different, you would need to swap the signatures
>   signedTxn.signIdx(secondSigner.privateKey!, 0);
> 
>   signedTxn.finalize();
> 
>   // this is the final signed transaction that you can broadcast
>   console.log("Final signed transaction:", signedTxn.hex);
> };
> 
> run();
> ```

Thank you. That's really helpful to me.

**Comment by mint-pz** [comment]
Hi @victorkirov , your example worked well with hot wallets, but when I tried with the ledger connected, it came with an error `Ledger device: Invalid data received (0x6a80)`. Any idea would much help!
