### ISSUE TITLE
Testnet4 support

### ISSUE THREAD

**Issue by mint-pz** [secretkeylabs/xverse-core#391]
I saw that we could customize URLs for Testnet. I'd like to know if it supports for testnet4?

<img width="352" alt="image" src="https://github.com/user-attachments/assets/628808e3-904a-44e2-8263-1014d27419fd">

**Comment by teebszet** [comment]
hi @mint-pz , this is currently testnet 3 support only! 

meanwhile we are preparing our infrastructure for testnet4, but no timeframe as of yet.

for now we suggest using Signet if you can 😄

**Comment by mint-pz** [comment]
> hi @mint-pz , this is currently testnet 3 support only!
> 
> meanwhile we are preparing our infrastructure for testnet4, but no timeframe as of yet.
> 
> for now we suggest using Signet if you can 😄

Thanks for your reply!
