### ISSUE TITLE
Stream timeout error

### ISSUE THREAD

**Issue by mint-pz** [secretkeylabs/xverse-core#392]
`signPsbt` method recently returns this error below on testnet, I found that it came from an API call request.

<img width="357" alt="image" src="https://github.com/user-attachments/assets/8a296818-cfda-4b33-a0e2-443551dec0f8">

<img width="952" alt="image" src="https://github.com/user-attachments/assets/e0bea661-2619-445b-9fd9-b418eeb05365">
Error response
<img width="952" alt="image" src="https://github.com/user-attachments/assets/fd40e332-04e6-437e-b18b-d7f28d574fbd">

**Comment by victorkirov** [comment]
Hey @mint-pz 

Testnet 3 is really unstable and some of the backing services are often stuck in an unrecoverable state, mostly due to reorgs. We'll be upgrading to testnet4 at some point. In the meantime, it's recommended to use Signet.
